SELECT * FROM customer LIMIT 20

--1.What is the total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender

--2.Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--3.Which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

--4.Compare the average purchase amount between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_status
COUNT(customer_id) as total_customers
ROUND(AVG(purchase_amount),2) AS avg_spend
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROU








